config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about', to: 'pages#about'
   resources :articles , only: [ :show, :index , :new, :create, :edit, :update, :destroy]


  get 'signup',  to: 'users#new'
   resources :users , expect: [:new]

  get 'login', to:'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
 validates :title, presence: true, length: {minimum:3, maximum:30}
 validates :discription, presence: true,length: {minimum:10, maximum:200}
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase}
  has_many :articles
  validates :username , presence: true,
                        uniqueness: { case_sensitive: false},
                         length: {minimum:3, maximum:20}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false},
                    length: { maximum:105 },
                    format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,:edit,:update,:destroy]
  def show
  end

  def index
    @articles =Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

   def update
      if @article.update(article_params)
        flash[:notice] = "Article was successfully updated"
        redirect_to @article
      else
        render 'edit'
      end
   end

   def destroy
     @article.destroy
     redirect_to articles_path, notice: "Article was successfully deleted."

   end


   private

   def  set_article
     @article = Article.find(params[:id])
   end

   def article_params
    params.require(:article).permit(:title,:discription)
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end



  def create
    user_params = params[:sessions]

    if user_params.present?
      user = User.find_by(email: user_params[:email])

      if user && user.authenticate(user_params[:password])
        session[:user_id] = user.id
        redirect_to user, notice: "Logged in successfully"
      else
        flash.now[:alert] = "Invalid email or password"
        render :new
      end
    else
      render :new
    end
  end





  def destroy
    session[:user_id] =nil
    flash[:notice] = "Logged Out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only:[:show,:edit,:update]
    def index
      @users = User.paginate(page: params[:page], per_page: 5)

    end

    def new
      @user = User.new
    end

    def show
      @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def update

      if @user.update(user_params)
        flash[:notice] = "Your user Update Successfully"
        redirect_to @user
      else
        render 'edit'
      end
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          flash[:notice] = "Welcome to the Alpha Blog,you have successfully sign-up"
          redirect_to articles_path

        else
            render 'new'
        end
    end


  private

  def user_params
    params.require(:user).permit(:username,:email,:password)
  end

  def set_user
    @user =User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
   email_address = user.email.downcase
   hash = Digest::MD5.hexdigest(email_address)
   size = options[:size]
   gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
   image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/password.rb
# email= amit@example.com password Amit@123

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
           <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.discription, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && article.user == current_user %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
   <% end %>
  </div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
          <%= render 'shared/errors',obj: @article %>

      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded",
                                     placeholder: "Title of article" %>
          </div>
        </div>

  <div class="form-group row">
          <%= f.label :discription, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :discription, rows: 10, class: "form-control shadow rounded",
                                                    placeholder: "Discription of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center" >
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
  <h1 class="text-center mt-4">Listing All Articles</h1>
<p>
  <%= link_to 'Create new article', new_article_path %>
</p>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

 <%= render 'article'%>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
        </div>

        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.discription) %></div>
          <% if logged_in? && @article.user == current_user %>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>

      </div>
    </div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Sumit dhoundiyal", "https://mashrurhossain.com",
                                class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if logged_in? %>
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
        <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>
         <form class="d-flex ms-auto" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
         </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/messages' %>
    <%= render 'layouts/navigation' %>

    <div id="page-content">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<p><%= link_to 'Articles listing', articles_path %></p>
<p><%= link_to 'Home Page', root_path %></p>
<!-- Paste this inside any layout or view for testing -->
<div class="dropdown m-5">
  <button class="btn btn-primary dropdown-toggle" type="button" id="testDropdown" data-bs-toggle="dropdown" aria-expanded="false">
    Test Dropdown
  </button>
  <ul class="dropdown-menu" aria-labelledby="testDropdown">
    <li><a class="dropdown-item" href="#">Action 1</a></li>
    <li><a class="dropdown-item" href="#">Action 2</a></li>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="container" id="home-container">
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
     <a class="btn btn-success btn-lg" href="<%= login_path %>" role="button">Log-In!</a>
     <a class="btn btn-success btn-lg" href="<%= signup_path %>" role="button">Sign up!</a>
  </div>
</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close"
    data-bs-dismiss="alert" aria-label="Close"></button>

  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
          <%= render 'shared/errors' ,obj: @user%>

      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
       <p> <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a Username" %>
          </div>
        </div>
        </p>

      <p>  <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "Enter your Email Address" %>
          </div>
        </div>
       </p>
        <p>
         <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a Password" %>
          </div>
        </div>
       </p>

        <div class="form-group row justify-content-center" >
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Alpha Bloggers</h1>
  <div class="flickr_pagination">
    <%= will_paginate @users, class: 'flickr_pagination' %>

  </div>

  <div class="container">
  <div class="container">
    <% @users.each do |user| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <%=link_to user.username, user %>
            </div>
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 150), user %>
              </h5>
              <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
              <%= link_to "View Profile", user, class: "btn btn-outline-success" %>
              <% if logged_in? and user == current_user %>
                <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </div>
    <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha _blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="ms-auto">
  <%= form_with url: logout_path, method: :delete, class: "d-flex", local: true do %>
    <button class="btn btn-outline-danger" type="submit">Logout</button>
  <% end %>
</div>

<h1 class="text-center mt-4"><%= @user.username %> 's profile </h1>

<%= gravatar_for @user, size: 200 %>
  <% if logged_in? && @user == current_user%>

    <div class="text-center mt-4">
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
    <% end %>

<h3 class="text-center mt-4"> Articles </h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>